server:
  port: 8081
spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/strr_admin?serverTimezone=UTC
    username: root
    password: password
mybatis:
  mapper-locations: classpath:mapper/*.xml, classpath:customMapper/*.xml
  configuration:
    map-underscore-to-camel-case: true