server:
  port: 8888
spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://${ipaddr}:3306/strr_admin?serverTimezone=UTC
    username: root
    password: '{cipher}b508a19f5f714b97916c70bd872da77208e5dca3da9830fefe9a1a50f683de9c'
  cloud:
    config:
      server:
        encrypt:
          enabled: false
        jdbc:
          sql: 'select `key`, `value` from sys_properties where application = ? and profile= ? and label = ?'
          sql-without-profile: 'select `key`, `value` from sys_properties where application = ? and profile is null and label = ?'
encrypt:
  key: secret
ipaddr: 127.0.0.1